### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by shinycolororange** [NerjalNosk/bettermaps#5] opened 2024-11-16 05:58 UTC
https://mclo.gs/vXP8jT3

**Comment by NerjalNosk** [comment] 2024-11-16 14:17
Caused by a [Unruled API](https://github.com/RecraftorsMC/Unruled-API) incompatibility with Mc 1.21+

Will be patched as soon as said mod fixes this incompatiblity

**Comment by NerjalNosk** [comment] 2024-11-20 00:48
Fixed with [Unruled#0.5.1](https://github.com/RecraftorsMC/Unruled-API/releases/tag/0.5.1%2B1.20), released in [0.6.0-SNAPSHOT.2](https://github.com/NerjalNosk/bettermaps/releases/tag/0.6.0-SNAPSHOT.2%2B1.21) (published as [0.6.0-beta.2](https://modrinth.com/mod/bettermaps/version/0.6.0-beta.2) on Modrinth)

**Closed as completed by NerjalNosk** 2024-11-20 00:48 UTC
Labels: incompatibility, 1.21
